export const FETCHING_COVID_19 = 'FETCHING_COVID_19';
export const FETCH_COVID_SUCCESS = 'FETCH_COVID_SUCCESS';
export const FETCH_COVID_FAILURE = 'FETCH_COVID_FAILURE';

export const FETCHING_COVID_COUNTRY_INFO = 'FETCHING_COVID_COUNTRY_INFO';
export const FETCH_COVID_COUNTRY_SUCCESS = 'FETCH_COVID_COUNTRY_SUCCESS';
export const FETCH_COVID_COUNTRY_FAILURE = 'FETCH_COVID_COUNTRY_FAILURE';

export const FETCHING_COUNTRY_LIST = 'FETCHING_COUNTRY_LIST';
export const FETCH_COUNTRY_LIST_SUCCESS = 'FETCH_COUNTRY_LIST_SUCCESS';
export const FETCH_COUNTRY_LIST_FAILURE = 'FETCH_COUNTRY_LIST_FAILURE';